version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5-stretch-node
        environment:
          RAILS_ENV: test
          DB_HOST: 127.0.0.1
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ROOT_PASSWORD: XXXXXXXX
    steps:
      - checkout
      - run:
          name: install bundler:2.1.4
          command: gem install bundler:2.1.4
      - run:
          name: Which bundler?
          command: bundle -v
      - restore_cache:
          paths:
            - .bundle
          keys:
            - gems-202003070127-{{ checksum "Gemfile.lock" }}
            - gems-202003070127-
      - run:
          name: bundle install
          command: |
            bundle config set deployment 'true'
            bundle config set path '.bundle'
            bundle install
      - save_cache:
          paths:
            - .bundle
          key: gems-202003070121-{{ checksum "Gemfile.lock" }}
      - run:
          name: DB を待機
          command: dockerize -wait tcp://localhost:3306 -timeout 1m
      - run:
          name: データベースをセットアップ
          command: bundle exec rails db:create db:schema:load --trace
      - run:
          name: RSpec を並列実行
          command: |
            bundle exec rspec --profile 10 \
                              --format RspecJunitFormatter \
                              --out test_results/rspec.xml \
                              --format progress \
                              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      - store_test_results:
          path: test_results

